### ISSUE TITLE
Gba bf does not work to write on this type of bootleg

### ISSUE THREAD

**Issue by graine2potiron** [lesserkuma/Custom_1M_FLASH_Patcher#1]
First thank you very much for this software and the work!
 Gba bf does not work to write on this type of bootleg, soo with what hardware / software could I write rom on this kind of bootleg (I have exactly the same as in the photo) ?

**Comment by Lesserkuma** [comment]
Hi, thanks! I currently use the GBxCart RW device with the FlashGBX software to write cartridges ^^

**Comment by graine2potiron** [comment]
Thank you very much for your quick response buddy! 
At this point and for leisure only, you might as well take an EZ Flash Gba, even the romhacks will work perfectly with it, wouldn't that be enough ?

**Comment by Lesserkuma** [comment]
Sorry, I don't understand the question.
